export const SPRINTS = [
  {
    number: 1,
    name: "Know Your Book",
    subtitle: "Book Segmentation & Service Prioritization",
    description: "Before you can grow or retain your book, you need to truly understand it. This sprint builds the habit of segmenting clients by complexity, revenue, and relationship health.",
    learningFileUrl: "https://media.base44.com/files/public/user_699b1700df38f0b040e28e0d/76761e467_AMAcceleratorKnowYourBookSprint.pdf",
    toolInstructions: "This project is your AI coaching partner for Sprint 1 of the AM Accelerator. It helps you segment your live book of business using a three-tier framework based on revenue, complexity, and relationship health -- so you know exactly where to focus your time and why.\n\nBy the end of this sprint, you will have a working tier map of your accounts, a clear picture of where your relationship risk lives, and a 30-day focus plan grounded in your actual book.",
    claudeProjectUrl: "https://claude.ai/project/019e404c-2021-70a3-b8a0-4377e67736d1",
    keyConcepts: [
      { title: "Client Segmentation", icon: "🎯", body: "Divide your book into Tier 1, Tier 2, and Tier 3 accounts based on revenue tier, relationship health, and complexity. Tier 1 accounts are your anchors — protect them. Tier 2 accounts are your growth opportunities. Tier 3 accounts require a deliberate decision and a clear plan of action." },
      { title: "Revenue vs. Complexity Matrix", icon: "📊", body: "Plot every account on a 2×2 grid: revenue on one axis, complexity on the other. High-revenue, low-complexity accounts deserve your most proactive energy. High-complexity, low-revenue accounts drain capacity without return." },
      { title: "Relationship Health Score", icon: "💚", body: "Evaluate each account on: last meaningful touchpoint, open issues, decision-maker access, and renewal sentiment. A client you haven't proactively called in 90+ days is a Tier 2 account regardless of revenue." },
      { title: "Weekly Book Review Habit", icon: "🔄", body: "Set a recurring Friday check-in: review the week's activity against your top 10 accounts. Ask — did I create value this week for my Tier 1 clients? Did I move any Tier 2 accounts forward?" },
      { title: "The CAM's Segmentation Mindset", icon: "🧠", body: "Segmentation isn't a one-time exercise — it's a living view of your book. Accounts shift tiers based on relationship health, renewals, and growth potential. The best CAMs re-evaluate quarterly." },
    ],
    reflectionQuestions: [
      { id: "q1", label: "Book Audit", prompt: "After segmenting your book, how many accounts did you categorize as Tier 1, Tier 2, and Tier 3? What surprised you most about the distribution?" },
      { id: "q2", label: "Hidden Opportunity", prompt: "Identify one Tier 2 account you've been treating like a Tier 1 account. What specific action will you take in the next 14 days to re-engage them proactively?" },
      { id: "q3", label: "Capacity Drain", prompt: "Which Tier 3 or high-complexity/low-revenue account is consuming the most time with the least return? What is your plan to resolve, restructure, or exit this relationship?" },
      { id: "q4", label: "Touchpoint Gap", prompt: "Which client in your top 10 have you not had a meaningful value-adding conversation with in the last 60 days? What will you say when you reach out this week?" },
      { id: "q5", label: "Growth Moment", prompt: "Describe one specific revenue-influenced or opportunity-uncovered moment from this sprint. What triggered the insight and what was the outcome?" },
    ],
  },
  {
    number: 2,
    name: "Positive, Proactive Client Outreach",
    subtitle: "From reactive service to proactive client experience management.",
    description: "68% of clients who leave say no one ever called them just to check in. This sprint builds your proactive outreach framework, touchpoint cadence, and the habits that make clients feel valued before they ask for help.",
    learningFileUrl: "https://media.base44.com/files/public/user_699b1700df38f0b040e28e0d/d6136bafa_Client_Service.pdf",
    toolInstructions: "This project is your AI coaching partner for Sprint 2 of the AM Accelerator. It helps you build and execute a proactive outreach plan for your book -- so your clients hear from you before something goes wrong, before renewal season hits, and before a competitor has reason to call.\n\nBy the end of this sprint, you will have a set of real, ready-to-send outreach messages for specific clients on your book, grounded in actual reasons to reach out.",
    claudeProjectUrl: "https://claude.ai/project/019e795d-49a8-75cb-8ed1-1d40c4ea99c1",
    keyConcepts: [
      { title: "The 4-Tier Response Framework", icon: "⚡", body: "Respond to client inquiries within defined windows: Tier 1 (critical/claims) — same day. Tier 2 (billing/endorsements) — 24 hours. Tier 3 (general questions) — 48 hours. Tier 4 (administrative) — 5 business days. Clients don't expect perfection — they expect communication." },
      { title: "The ACE Model for Issue Resolution", icon: "🎖️", body: "Acknowledge the issue without blame. Commit to a timeline, not an answer. Execute and follow up even when the news isn't good. The ACE model separates reactive AMs from trusted advisors." },
      { title: "Owning Coverage Questions", icon: "📋", body: "Never say 'I'll have to check the policy' and disappear. Say: 'Let me pull the policy and get you a clear answer by [specific time].' Then deliver. Bounded commitments build trust faster than vague reassurances." },
      { title: "COI & Endorsement Discipline", icon: "📄", body: "Certificates and endorsements have legal weight. Confirm: correct additional insured wording, proper effective dates, and carrier authority before issuing. A mistake here creates E&O exposure and erodes client trust permanently." },
      { title: "Escalation with Grace", icon: "🤝", body: "When a client escalates, they're not attacking you — they're scared. De-escalate with empathy first: 'I hear you and I understand why this is frustrating.' Then shift to action: 'Here's exactly what I'm going to do in the next 2 hours.'" },
    ],
    reflectionQuestions: [
      { id: "q1", label: "Service Inventory", prompt: "List the 3 most common service requests you receive. For each one, do you have a documented response process or do you recreate it every time? What would a documented process change?" },
      { id: "q2", label: "ACE in Action", prompt: "Describe a recent client issue you resolved. How did you apply (or wish you had applied) the Acknowledge-Commit-Execute framework? What would you do differently?" },
      { id: "q3", label: "Response Time Reality", prompt: "Honestly assess your average response time to Tier 1 and Tier 2 requests this sprint. Where did you exceed the standard? Where did you fall short and why?" },
      { id: "q4", label: "The No-Promise Principle", prompt: "Describe a moment when you were tempted to give a client an answer before confirming it in the policy. How did you handle it? What's your personal rule for coverage questions now?" },
      { id: "q5", label: "Service-to-Revenue Link", prompt: "How did strong service create a revenue opportunity or protect a renewal during this sprint? Describe the situation and the outcome." },
    ],
  },
  {
    number: 3,
    name: "The Renewal Conversation",
    subtitle: "Plan, prepare, and lead a strategic renewal from 90 days out.",
    description: "Most AMs react to renewals — the best ones orchestrate them. This sprint builds your 5-phase renewal process, pre-renewal conversation framework, and the habits that turn a transaction into a retention strategy.",
    learningFileUrl: "https://media.base44.com/files/public/user_699b1700df38f0b040e28e0d/22a55b0b9_Coverage_review.pdf",
    toolInstructions: "Choose an account that: \n(1) renews within the next 90-180 days\n(2) has at least some complexity - multi-line, claims history, or a relationship that needs attention\n(3) is an account where your renewal approach could genuinely improve. Avoid picking your easiest account. The brief is most valuable where the stakes are real.\n\nIntroduce your account to the Claude coach: industry, size, lines of coverage, renewal date, and a brief description of the relationship. Be specific the more real detail you provide, the more useful the coaching will be.\n\nWork through the Renewal Strategy Brief with your Claude coach. Let the Claude coach guide you through each section of the brief. It will ask you questions -- answer them as honestly and specifically as you can.",
    claudeProjectUrl: "https://claude.ai/project/019e796d-de0c-7257-a3be-54ca3191deae",
    keyConcepts: [
      { title: "The Gap-Hunting Mindset", icon: "🔍", body: "Coverage review isn't about confirming what's there — it's about finding what's missing. Start every review with the question: 'What would hurt this client most if it happened today and wasn't covered?' Work backwards from the risk." },
      { title: "Coverage Summary Document", icon: "📑", body: "Every client should have a one-page Coverage Summary: lines of coverage, key limits, deductibles, exclusions to note, and gaps. This document drives stewardship meetings and renewal conversations. If you don't have one for your top 10 accounts, start today." },
      { title: "Reading for Risk Language", icon: "📖", body: "Focus on: exclusions (what's out), conditions (what triggers coverage), definitions (how terms are narrowly defined), and sublimits (where real limits hide). The endorsements section often contains the most important client-specific modifications." },
      { title: "Translating Policy to Client Risk", icon: "💬", body: "Clients don't read policies — they trust you to. Your job is to translate: 'Your current cyber policy has a $50K sublimit for business interruption but your daily revenue exposure is $200K' is more powerful than citing the policy section number." },
      { title: "The Pre-Renewal Coverage Conversation", icon: "📅", body: "90 days before renewal, initiate a coverage conversation — not a renewal conversation. Ask: 'Has anything changed in your operations this year?' Changes in payroll, new contracts, new locations, or new equipment all have coverage implications." },
    ],
    reflectionQuestions: [
      { id: "q1", label: "Timeline Gap Analysis", prompt: "When you mapped out your renewal timeline for this account, how far out were you actually planning to start -- versus how far out the sprint suggests? What accounts for the gap, if there is one? Think about what drove your previous approach. Was it habit, bandwidth, the client's behavior, or something else?" },
      { id: "q2", label: "Value Demonstration", prompt: "When you listed your value demonstration points, what felt easy to name and what felt hard? What does that tell you about how you are stewarding this account? If you struggled to name two things, that is the insight not a failure to complete the exercise." },
      { id: "q3", label: "Renewal Challenges", prompt: "What is the hardest part of this renewal -- and is it something you can actually influence between now and the effective date? Separate what is in your control from what is not. Where will you focus your energy?" },
      { id: "q4", label: "Pre-Renewal Authenticity", prompt: "Review the pre-renewal conversation agenda. Are these questions you would actually ask, or questions that sound right on paper? What would stop you from asking them? The gap between what we know to ask and what we actually ask in the moment is where most renewal conversations fall short." },
      { id: "q5", label: "Next Renewal Commitment", prompt: "Based on this sprint, what is one specific thing you will do differently on the next renewal you manage? Name the account, name the behavior, and name when you will start." },
    ],
  },
  {
    number: 4,
    name: "Spot the Gap",
    subtitle: "Round out accounts and grow revenue through advisory cross-selling.",
    description: "Your best new business is already in your book. This sprint trains you to score account roundness, frame cross-sell conversations as risk advisory, and partner with your SAE on warm handoffs.",
    learningFileUrl: "https://media.base44.com/files/public/user_699b1700df38f0b040e28e0d/1c96fc4c3_CrossSell_RoundingOutAccounts.pdf",
    toolInstructions: "Sprint 4 reframes cross-selling as a core account management responsibility -- not a sales activity. When a client has an uninsured exposure, they typically do not know it. You do. That asymmetry makes identifying and addressing coverage gaps a professional obligation, not an upsell opportunity. This sprint gives you a structured way to act on that obligation.\n\nThe sprint covers the Coverage Gap framework (organized by EB, CL, and PL client types), the Account Roundness Score for book-level prioritization, the four-question diagnostic conversation, the mindset shift from sales pitch to risk advisory, and how to handle the four most common client objections. The sprint activity applies these tools to three real accounts on your book so the output is a working cross-sell action plan -- not a worksheet.",
    claudeProjectUrl: "https://claude.ai/project/019e797b-ac6e-73c4-a78e-c79af716f49e",
    keyConcepts: [
      { title: "Account Roundness Score", icon: "🎯", body: "Score each account by lines of business placed at HUB: 1 line = 20%, 2 lines = 40%, and so on. An account with 5+ lines is 'fully rounded.' Your lowest-scoring accounts with the strongest relationships are your highest-priority cross-sell targets." },
      { title: "The Risk Advisory Frame", icon: "🛡️", body: "Never lead with 'Can I quote you on your auto?' Lead with: 'I was reviewing your account and noticed you don't have [line] — given your operations, that could expose you to [specific risk]. Can I put together a brief analysis?' Advisory framing outperforms sales framing every time." },
      { title: "The Diagnostic Conversation", icon: "💡", body: "Before cross-selling, diagnose. Ask: 'Where does your business have the most exposure you're least sure about?' 'What insurance relationships do you have outside of HUB?' 'If something happened tomorrow in [area], are you confident you're covered?' Listen more than you pitch." },
      { title: "SAE Warm Handoff Protocol", icon: "🤝", body: "A warm handoff isn't a cold transfer. It requires: context briefing to the SAE (client history, relationship, opportunity), a joint client touchpoint, and a post-meeting debrief. You stay in the relationship as the CAM — the SAE brings expertise." },
      { title: "Timing the Cross-Sell", icon: "⏱️", body: "The best cross-sell moments: post-claim resolution, 90 days pre-renewal, post-stewardship meeting with positive feedback, and after a client mentions a business change. These are trust peaks — capitalize on them." },
    ],
    reflectionQuestions: [
      { id: "q1", label: "Roundness Surprises", prompt: "When you ran the Account Roundness Score on your three accounts, what surprised you? Was there a gap you had not considered, or a client you had assumed was well-covered that turned out not to be? Surprise is a signal. If you did not know the gap existed, the client almost certainly doesn't either." },
      { id: "q2", label: "Barriers to Coverage Conversations", prompt: "What stopped you from having a coverage gap conversation with these accounts before this sprint? Be specific -- was it not knowing what to look for, not knowing how to raise it, or something else? The barrier is almost always one of three things: visibility, language, or confidence. Naming yours is the first step to addressing it." },
      { id: "q3", label: "Authentic Conversation Starters", prompt: "Look at the diagnostic conversation starters you wrote in Step 3. Do they sound like you, or do they sound like a script? What would you actually say to open this conversation with this specific client? The best opening question is one you could say naturally, in your own voice, without looking at a document." },
      { id: "q4", label: "Uncovered Loss Moment", prompt: "Think about the last time a client on your book experienced a claim in an area that HUB did not cover. What happened? What would a coverage gap conversation earlier have changed?" },
      { id: "q5", label: "Role Definition", prompt: "How does this sprint change how you think about your role as an AM? Is 'identifying coverage gaps' something you see as part of your job description -- and if not, what would need to change for it to become one?" },
    ],
  },
  {
    number: 5,
    name: "Handle It",
    subtitle: "Turn difficult conversations into retention moments.",
    description: "Clients judge their entire insurance relationship based on how their claims are handled. This sprint builds your claims process fluency, communication scripts, and escalation protocols.",
    learningFileUrl: "https://media.base44.com/files/public/user_699b1700df38f0b040e28e0d/3e817fbdf_claims_advocacy.pdf",
    toolInstructions: "Sprint 5 addresses one of the highest-stakes, most avoided parts of the AM role: difficult client conversations. The core reframe is this -- clients do not leave because something went wrong. They leave because of how it was handled. A service failure addressed with honesty, speed, and a clear path forward builds more loyalty than three years of smooth renewals. The AM who can walk into a hard conversation with a framework and confidence comes out with a stronger relationship.",
    claudeProjectUrl: "https://claude.ai/project/019e7989-5387-717d-ba68-0010cb409d95",
    keyConcepts: [
      { title: "The ANCHOR Framework", icon: "⚓", body: "Acknowledge the stress of the situation. Navigate the client through next steps. Confirm who owns each action item. Highlight the timeline for resolution. Observe and update proactively — don't wait to be asked. Reinforce the relationship after resolution." },
      { title: "Claims Communication Cadence", icon: "📡", body: "Communicate with clients at minimum: within 24 hours of first notice, at every status change, and when there's no update (proactive silence-breaker). The biggest client complaint in claims is 'no one told me what was happening.' You own this." },
      { title: "The Advocacy Mindset", icon: "⚔️", body: "Advocacy means you're actively working the claim — not just passing information. Know the carrier's desk adjuster. Understand the reserve amount and whether it's adequate. Push back on denials that are defensible. Your client hired HUB partly to have a fighter in their corner." },
      { title: "Escalation Without Burning Bridges", icon: "🌉", body: "When you need to escalate with a carrier, frame it as 'help me understand' not 'you're wrong.' Say: 'I want to make sure I'm presenting this correctly to my client — can you walk me through the basis for this decision?' Preserve the relationship while advocating for your client." },
      { title: "Post-Claim Stewardship", icon: "🌱", body: "Every significant claim is a relationship-defining moment. Within 30 days of resolution, conduct a post-claim review with the client: 'Let's talk about what happened, what the claim process looked like, and what we can do to prevent or prepare for this in the future.'" },
    ],
    reflectionQuestions: [
      { id: "q1", label: "Default Behavior Pattern", prompt: "Before this sprint, what did you typically do when a difficult client conversation was coming? Prepare specifically, avoid it as long as possible, handle it on instinct, or something else? There is no wrong answer here -- but naming your current default is the first step to changing it intentionally." },
      { id: "q2", label: "Hardest Scenario Type", prompt: "Which of the three scenario types is hardest for you personally - service failures, rate increases, or retention risk? What makes that one feel different from the others? The type that feels hardest is usually the one where you are least sure what you own and what you don't." },
      { id: "q3", label: "CLARA Step Challenge", prompt: "When you drafted your CLARA walkthrough for your most difficult scenario, which step felt hardest to write? C (the opening acknowledgment), L (listening to understand), A (acknowledging impact without over-apologizing), or R (making a specific commitment when you don't have all the answers)? The step that is hardest to write is usually the step that is hardest to execute under pressure. That is the one to practice most." },
      { id: "q4", label: "Past Success Pattern", prompt: "Think about a time in your career when a difficult conversation went well -- when the client ended the call or meeting in a better place than when it started. What did you do that made that happen? You likely already have some of this skill. The question is whether you can deploy it consistently, under pressure, with a framework behind it." },
      { id: "q5", label: "Mindset Shift", prompt: "How does this sprint change how you think about service failures and client pushback? Do difficult conversations feel more like a threat to the relationship or more like a test of it? This is the sprint's core question. Mindset is not just attitude -- it changes the language you use, the speed with which you respond, and what you do after." },
    ],
  },
  {
    number: 6,
    name: "The Business Review",
    subtitle: "Demonstrate value and drive retention through structured client reviews.",
    description: "Clients who can't articulate what you do for them are flight risks. This sprint builds your ability to conduct structured business reviews that shift the conversation from activity to outcomes — making your value impossible to ignore at renewal.",
    learningFileUrl: "https://media.base44.com/files/public/user_699b1700df38f0b040e28e0d/73b9d6c82_Carrier_Market_Relationships.pdf",
    toolInstructions: "Sprint 6 focuses on one of the most underdeveloped habits in account management: communicating the value of the work you have already done. Most AMs do significantly more for their clients than clients are aware of -- claims advocated, renewals challenged, compliance issues caught, vendors held accountable. None of it influences retention unless it is communicated. The business review is the structured moment that makes all of it visible.\n\nThe sprint covers the core reframe (showing your work vs. assuming clients notice it), the six review components organized by practice area (EB, CL, and PL), a four-part review structure (what we've done / what we're working on / what's coming / your feedback), and the critical skill of framing outcomes rather than listing activities. The sprint activity produces a real Business Review Prep -- a structured document you can use to run an actual review with one account on your book.",
    claudeProjectUrl: "https://claude.ai/project/019e7998-7181-7585-adc5-9cacc0b45ab9",
    keyConcepts: [
      { title: "Carrier Contact Map", icon: "🗺️", body: "Build a map of your key carriers: underwriter name, desk adjuster, appetite sweet spots, current relationship quality (1-5), and last meaningful touchpoint date. A CAM who knows their underwriter personally gets the benefit of the doubt at renewal." },
      { title: "Understanding Carrier Appetite", icon: "🎯", body: "Each carrier has a sweet spot: class of business, revenue range, geography, and loss history they'll compete for. Understanding this means you can pre-screen submissions and have a conversation before you send paper. 'I have an account I think is in your wheelhouse — let me tell you why.'" },
      { title: "Relationship-Based Renewals", icon: "🔄", body: "The renewal conversation with your carrier starts 120 days out — not 30. Touch base mid-term just to connect: share positive developments at the account, alert them to changes, and ask what's happening in their book. This is the currency you spend at renewal." },
      { title: "The Difficult Market Conversation", icon: "💪", body: "When markets tighten, your job is to coach your client before they experience the shock. Say: 'I want to prepare you for what I'm seeing in the market — before I go out and get quotes, let me tell you what underwriters are focused on right now.' Preparation protects trust." },
      { title: "Mid-Term Advocacy Protocol", icon: "📞", body: "When a client has a mid-term issue (new exposure, certificate request requiring carrier approval, endorsement), your carrier relationship is what speeds up resolution. Informal contacts — knowing the right person — cuts timelines from days to hours." },
    ],
    reflectionQuestions: [
      { id: "q1", label: "Activity to Outcome Translation", prompt: "When you built Part 1 of the review, how difficult was it to turn what you did into what the client gained? Where did the language feel natural, and where did you find yourself defaulting back to activity statements? The gap between activity language and outcome language is a proxy for how you think about your role. If outcome framing felt hard, that is the skill to develop -- not just for reviews, but for every client conversation." },
      { id: "q2", label: "Client Value Perception", prompt: "Think about the account you chose for this sprint. Before building the prep, how confident were you that this client truly understood the value of the HUB relationship? After building it, has that assessment changed? This question goes to retention. Clients who understand what they have do not shop casually." },
      { id: "q3", label: "Risky Feedback Questions", prompt: "When you wrote the plus/delta questions for Part 4, did any of them feel risky to ask -- like an honest answer might reveal something uncomfortable? What does that tell you about this relationship or this account? The questions that feel risky are often the most important ones to ask. If you are avoiding a feedback conversation, you are probably already behind." },
      { id: "q4", label: "Broader Application", prompt: "Is there another account on your book where you know the value story is strong but the client does not see it -- and where a business review would make a significant difference? The habit of annual reviews is the outcome of this sprint -- not just this one prep document." },
      { id: "q5", label: "Stewardship Habits", prompt: "How does this sprint change how you will approach stewardship between now and the next renewal for this account? Is there anything you will do differently during the year to make next year's review content stronger? The best business review content is built continuously, not assembled in a hurry. What you document during the year is what you can show at the review." },
    ],
  },
  {
    number: 7,
    name: "Build a Better Submission",
    subtitle: "Create compelling submissions that win underwriter attention and priority.",
    description: "Underwriters prioritize the submissions that make their job easy. This sprint builds your ability to assemble complete, well-framed submissions — with strong cover memos, clean data, and a narrative that positions your account to win.",
    learningFileUrl: "https://media.base44.com/files/public/user_699b1700df38f0b040e28e0d/d98577b5d_ClientCommunication.pdf",
    toolInstructions: "Sprint 7 focuses on one of the most technically concrete skills in the AM role: building submissions that underwriters want to quote. Submission quality is a direct proxy for your knowledge of the account and your professionalism as a broker. The underwriter who receives a clean, complete, well-narrated package gives it priority. The one who receives a half-built submission quotes it conservatively -- or declines to quote it at all. This sprint teaches you to be the broker who gets the first call back.",
    claudeProjectUrl: "https://claude.ai/project/019e79a7-13f8-73ee-957e-15f581878959",
    keyConcepts: [
      { title: "The 90-Day Touchpoint Cadence", icon: "📅", body: "Every Green account should receive a meaningful touchpoint at least every 90 days. Meaningful means value-adding: an industry update, a coverage insight, a risk alert, or a check-in call with a specific agenda. An email saying 'just checking in' doesn't count." },
      { title: "The SCORE Framework", icon: "🎯", body: "Structure stewardship meetings with SCORE: Situation (where the client is today), Changes (what's shifted in their operations or risk), Opportunities (where you see gaps or growth), Renewal preview (what to expect), and Expectations (confirm next steps and timelines). A 45-minute SCORE meeting builds more loyalty than 12 months of reactive service." },
      { title: "Written Communication Standards", icon: "✍️", body: "Every client-facing email should have: a clear subject line that states the purpose, a one-sentence summary at the top, action items clearly labeled, and a defined response expectation. Long emails hide the point. Short emails with clear asks get answered." },
      { title: "Value-Add Communication", icon: "💎", body: "The best CAMs share industry insights before clients ask: 'I saw this emerging risk trend and thought of your operations,' or 'The cyber market is shifting and I want to brief you before renewal.' Being the source of relevant information makes you irreplaceable." },
      { title: "Decision-Maker Access Strategy", icon: "🔑", body: "Map your clients' decision-making structure: who signs the check, who influences the decision, who will block a change. If you only have relationships at the service level, your renewal is vulnerable. Build access to the CFO, COO, or owner through stewardship meetings." },
    ],
    reflectionQuestions: [
      { id: "q1", label: "Completeness Audit", prompt: "When you ran the completeness audit on your account, what gaps surprised you? Were there required elements you had not thought to include, or items you knew were missing but had not yet chased down from the client?" },
      { id: "q2", label: "Risk Narrative Framing", prompt: "When you wrote the risk narrative for your account, was there anything you found difficult to frame? A claim, a carrier change, a complicated history? How did you ultimately choose to address it in the narrative?" },
      { id: "q3", label: "Broader Application", prompt: "Is there another account on your book where submission quality has likely been affecting the terms you are getting back? What would you do differently on that submission?" },
      { id: "q4", label: "Underwriter Questions", prompt: "Think about the last time an underwriter came back to you with questions before quoting -- asking for information you should have included in the original submission. What would have changed if that information had been in the cover memo? Every follow-up question from an underwriter is a signal that the submission was incomplete. It costs time, delays terms, and erodes the impression you make." },
      { id: "q5", label: "Underwriter Relationship", prompt: "How does this sprint change how you think about your relationship with underwriters? Are they people you market to, or people whose job you are actively making easier? What is the difference in terms of what you do and what you get back? The broker who makes underwriting easy gets priority, callbacks, and better terms over time. That is a competitive advantage built one submission at a time." },
    ],
  },
  {
    number: 8,
    name: "Support the Producer",
    subtitle: "Align with producers and mobilize HUB resources for book growth.",
    description: "The AM who only manages their task list will plateau. The AM who operates as a team asset will grow. This sprint focuses on aligning with producers, mobilizing HUB resources, and contributing to book growth.",
    learningFileUrl: "https://media.base44.com/files/public/user_699b1700df38f0b040e28e0d/849b3af03_InternalCollaboration.pdf",
    toolInstructions: "Sprint 8 is the capstone of the AM Accelerator, the sprint that connects everything that came before it to how you show up within your team. The core reframe is this: the best AMs are not solo operators. They are the person in the room who knows the client best and who has the professional responsibility to make sure that knowledge gets to the right places. When you share what you know with the producer, activate the right specialist, or flag a risk before it becomes a problem, you are doing your job at the highest level. Not selling. Serving.",
    claudeProjectUrl: "https://claude.ai/project/019e79c7-10de-74c0-9e46-ae0a12b596c9",
    keyConcepts: [
      { title: "Account Ownership Map", icon: "🗺️", body: "For each account in your top 20, document: Producer name, frequency of joint touchpoints, last strategic conversation about the account, and your assessment of their involvement level. A CAM who treats each account as a shared asset — not a solo task — retains more and grows more." },
      { title: "Producer Alignment Conversations", icon: "🤝", body: "Don't wait for producers to come to you. Initiate a quarterly alignment call on your shared accounts: 'Here's what I'm seeing, here's what I'm working on, here's where I need your involvement.' Producers partner more deeply with CAMs who communicate proactively about their book." },
      { title: "Mobilizing HUB Resources", icon: "⚡", body: "HUB has risk engineering, specialty practices, loss control, analytics, and claims advocacy resources. Most AMs never use them. Identify one client in your book who would benefit from a specialty practice introduction and make that call this sprint." },
      { title: "The Growth Mindset CAM", icon: "📈", body: "The best CAMs see themselves as book growth partners — not just service providers. When a producer closes new business in your class, ask to be briefed. Offer to co-lead the onboarding. Build a reputation as the CAM who makes producers' new accounts succeed." },
      { title: "Internal Communication Discipline", icon: "📬", body: "Keep producers informed without overwhelming them: flag important client changes immediately, summarize open items weekly, and never surprise a producer about a client issue they should have known about. Trust is built internally the same way it's built with clients — through reliable, timely communication." },
    ],
    reflectionQuestions: [
      { id: "q1", label: "Collaboration Failure Patterns", prompt: "When you assessed your three accounts for the four collaboration failures, which failure was most common across your book — siloed renewal work, late escalations, not using internal resources, or ownership ambiguity? What do you think is driving that pattern?" },
      { id: "q2", label: "Producer Perception", prompt: "Think about your current producer relationship. How would your producer describe how you communicate with them? Would they say you bring intelligence, or just status updates? That you flag things early, or that issues arrive fully formed and urgent?" },
      { id: "q3", label: "Flagged Signal", prompt: "Is there a client signal on one of your accounts that you have noticed but not yet shared with your producer — and if so, what has stopped you? What will you do about it this week?" },
      { id: "q4", label: "Biggest Gap", prompt: "Looking back across all eight sprints — book management, proactive outreach, renewal management, cross-sell, difficult conversations, the business review, submissions, and internal collaboration — which sprint surfaced the most significant gap between how you were operating and how you want to operate? What has changed since then?" },
      { id: "q5", label: "Habit for Impact", prompt: "Which one habit built consistently would have the biggest impact on the quality of service your clients receive over the next 12 months? What would need to be true for that habit to stick?" },
    ],
  },
  {
    number: 9,
    name: "Capstone",
    subtitle: "Account Strategy Presentation",
    description: "Select one client from your active book and deliver a structured Account Strategy Presentation demonstrating everything built across the eight sprints.",
    learningFileUrl: null,
    toolInstructions: "Use the AI Sprint Tool to prepare your Capstone Account Strategy Presentation.",
    claudeProjectUrl: "https://claude.ai/project/019eaafb-307c-727a-a4d8-28779d006082",
    keyConcepts: [
      { title: "Capstone Account Selection", icon: "🏆", body: "Choose a client that represents your best work — or your biggest opportunity. The account should have enough complexity to demonstrate multiple sprint competencies: segmentation, coverage review, cross-sell thinking, communication, and carrier strategy." },
      { title: "Presentation Structure", icon: "📋", body: "Your presentation should cover: Client Overview (segment, revenue, relationship health), Coverage Analysis (gaps identified, changes made), Service Record (major issues handled, response quality), Growth Strategy (cross-sell opportunities pursued or planned), and Carrier & Market Positioning." },
      { title: "Demonstrating Strategic Thinking", icon: "🧠", body: "The Capstone isn't a report — it's a demonstration of how you think about a client. Connect every section back to the client's business risk and your role as a trusted advisor. Show how your actions created value, not just completed tasks." },
      { title: "The Leader Review", icon: "👥", body: "Your Capstone will be reviewed with your leader. Come prepared to discuss: what you're most proud of, where you see the biggest opportunity for growth, and what you would do differently in the next 90 days with this account." },
      { title: "90-Day Forward Action Plan", icon: "🚀", body: "The most important section: what comes next. Define 3 specific, measurable actions you will take with this account in the next 90 days. Tie each action to a sprint framework you've built. This is your commitment to continued growth." },
    ],
    reflectionQuestions: [
      { id: "q1", label: "Account Selection Rationale", prompt: "Which client did you select for your Capstone and why? What makes this account the best demonstration of your growth across the 8 sprints?" },
      { id: "q2", label: "Biggest Transformation", prompt: "What is the single biggest change in how you think about and manage this account compared to when you started the CAM Accelerator? Give a specific example." },
      { id: "q3", label: "Sprint Integration", prompt: "Walk through at least 3 sprints and describe how you applied the frameworks to this specific account. Be concrete — what did you do, what changed, and what was the result?" },
      { id: "q4", label: "Honest Assessment", prompt: "What is one area of your AM practice that still needs significant development? What specific steps are you committing to after this program to address it?" },
      { id: "q5", label: "Forward Commitment", prompt: "List your 3 specific, measurable 90-day action items for your Capstone account. For each, name the sprint framework you're applying and define what success looks like." },
    ],
  },
];

export const SPRINT_LABELS = {
  1: "Sprint 1",
  2: "Sprint 2",
  3: "Sprint 3",
  4: "Sprint 4",
  5: "Sprint 5",
  6: "Sprint 6",
  7: "Sprint 7",
  8: "Sprint 8",
  9: "Capstone",
};